f=open("./files/testimage1.jpg", 'rb')
data1=f.read()
f.close()
f=open("./files/testimage2.jpeg", 'rb')
data2=f.read()
f.close()
f=open("./files/testimage3.png", 'rb')
data3=f.read()
f.close()
f=open("./tests/Allimage.out", "wb")
f.write(data1)
f.write(data2)
f.write(data3)
f.close()